# config.py
from pathlib import Path


# Define the configuration settings for the ModelManager service
class Settings:
    APP_DIR: Path = Path(__file__).parent.parent
    MODEL_PATH: Path = APP_DIR / "ai" / "model"
    DISTIL_MODEL = ""
    MEDICARE_MODEL = ""
    MEDICARE_MODEL_B = ""
    MEDICARE_MODEL_11 = ""
    MEDICARE_MODEL_12 = ""
    ACA_MODEL = ""
    FE_MODEL = ""
    FE_MODEL_B = ""
    ACA_MODEL_B = ""
    ACA_MODEL_C = ""
    WHISPER_MODEL = "openai/whisper-tiny.en"
    TOKENIZER_PATH: Path = APP_DIR / "ai" / "tokenizer"
    MODEL_LOAD_FILEPATH: Path = APP_DIR / "core" / "whisper_test.wav"
    MODEL_FILE_ID = ""
    MODEL_COUNT: int = 2
    TYPE = True

    EXACT_SEARCH_DICT = {
        "HP": [
            "good okay um",
            "hedge",
            "greetings",
            "so uh alright",
            "oh good yes yes yes",
            "sorry i can barely hear you there",
            "likewise",
            "okay so alright it's",
            "go ahead and do it",
            "computer don't compute",
            "hello alright",
            "i'm a robot",
            "who would you like to speak with anyway",
            "excuse me who did you say this was",
            "thank you bye hello",
            "uh huh yep",
            "sure tell me",
            "i hope this isn't a telemarketing call",
            "i didn't hear you what did you say",
            "alright and i'm assuming everything 'cause we did",
            "try this a couple",
            "keeps going on",
            "i'm not interested and don't call me back",
            "quit this",
            "of course dumbass you motherfuckers call all day every day",
            "of course don't ask you motherfuckers call all day every day",
            "i'm not that age yet",
            "you gotta get you gotta call me back",
            "but I don't even know what y'all talking about",
            "my son takes care of all that for me thank you",
            "you got to get you got to call me back",
            "oh I'm fine as a matter of fact",
            "i'm 91 no I'm 92 now",
            "oh I'm fine as a matter of fact how are you",
            "define how you do it",
            "motherfuckers call all day every day",
            "well I don't y'all don't want to call me",
            "of course dumbass you motherfuckers call all day everyday",
            "don't call that's the",
            "please call it please",
            "alright uh okay so uh alright",
            "alright uh okay so um alright",
            "okay so uh alright",
            "alright uh okay so uh",
            "uh okay so uh",
            "okay so all right",
            "okay so alright",
            "okay alright",
            "good okay",
            "ha ha ha ha okay",
            "oh guys come on",
            "ha ha okay",
            "ha ha ha okay",
            "free i didn't hear you",
            "don't disappear on me",
            "and do it",
            "yeah they make this very oh guys come on",
            "okay okay okay",
            "okay uh",
            "ha ha ha ha ha okay",
            "i'm listeninghow are you i'm doing very well",
            "are you there can you hear me",
            "okay there's a couple of things that",
            "good word",
            "i'm 58",
            "my son takes care of all that for me",
            "to get with my son and see what he says but thank you for calling",
            "interested and don't call me back",
            "don't call that there",
            "it and don't call me back",
            "stop calling",
            "not interested and don't call me back",
            "yeah you can hold it for me for a moment",
            "okay so what do i need to do",
            "i don't have any idea i'll have to get with my son and see what he's",
            "an idea i'll have to get with my son and see what he says",
            "any idea i'll have to get with my son and see what he says",
            "i'll have to get with my son and see what he says",
            "i don't have any idea i'll have to get with my son and see what he's doing",
            "well you go ahead and do that without me",
            "so i'm sorry i've declined at this time",
            "decline at this time",
            "i'm sorry i've to decline at this time",
            "a decline at this time",
            "oh i'm not interested in anything honey",
            "no no no goodbye goodbye to my mate",
            "i don't love you",
            "no no no goodbye goodbye to the me",
            "no no no goodbye right and i'm me",
            "no no no goodbye goodbye to the meat",
            "okay bye bye",
            "non-takes care of all that for me thank you",
            "no no no goodbye right and i meet",
            "i don't know okay",
            "i don't know okay but",
            "from where you are calling me",
            "you know you got to get you got to call me back",
            "you gotta get and you gotta call me back",
            "i don't have any idea i'll have to get with my son and see what he says",
            "get you got to call me back",
            "so you gotta get you gotta call me back",
            "don't have any idea i'll have to get with my son and see what he says",
            "i don't have any idea i'll have to get with my son and see what--",
            "care of all that for me thank you",
            "takes care of all that for me thank you",
            "all that for me thank you",
            "the sun takes care of all that for me thank you",
            "john takes care of all that for me thank you",
            "I don't have any idea I'll have to get with my son and see what he says but thank you for calling",
            "don't call that guy",
            "but i know y'all don't want to call me",
            "well i know y'all don't want to call me",
            "i know y'all don't want to call me",
            "don't call that",
            "why did you want to know",
            "is probably a scam",
            "calling me far enough man",
            "ok so what do i need to do",
            "what do i need to do",
            "yeah you can hope it's so much better",
            "goodbye to my son on me",
            "with my son and see what he says but thank you for calling",
            "so i'm sorry i've to decline at this time",
            "new england facility",
            "state your business",
            "where you're calling me for now man",
            "please tell me more",
            "i must be a fraud i don't know",
            "where are you located",
            "what company do you represent",
            "please say your name",
            "please say your name the legal name",
            "please say your name the legal name of the entity",
            "the legal name of the entity",
            "please say your name the legal name of the entity responsible for the call and your contact address "
            "and phone number",
            "the legal name of the entity responsible for the call",
            "name of the entity responsible for the call and your contact address and phone number",
            "I didn't consent to this call",
            "I didn't consent to this call say your legal company name location call back number",
            "this call is guaranteed to be spoofed the calling party number in this case is unassigned and "
            "never makes any outbound calls therefore there's no valid justification any outbound calls from "
            "this number",
            "this call is guaranteed to be spoofed",
            "the calling party number in this case is unassigned and never makes any outbound calls",
            "therefore there's no valid justification any outbound calls from this number",
            "the calling party number in this case is unassigned and never makes any outbound calls therefore "
            "there's no valid justification any outbound calls from this number",
            "please fully describe your product or service",
            "I didn't consent to this call",
            "I didn't consent to this call say your legal company name location call back number",
            "tell me more",
            "keep going give me your pitch",
            "keep going",
            "give me your pitchmy son takes care of all that for me thanks",
            "i'm listening",
            "don't know what that means",
            "is this call being recorded",
            "i don't know what that means",
            "big mistake so what's your address and where you located",
            "i told you i didn't give my consent and you're telling me that it's being recorded still",
            "made a big mistake so what's your address and where are you located",
            "get my number",
            "because i don't consent to being recorded you didn't tell me that that's a big no-no",
            "this is an unwanted call don't call again i've not requested this call nor given consent for it "
            "i've no overdue debts i don't do surveys",
            "you just made a big mistake so what's your address and where you located",
            "i don't consent to be recorded and you didn't tell me that that's a big no-no",
            "know what that means",
            "what that means",
            "mistake so what's your address and where are you located",
            "got my number",
            "i don't consent to be recorded and you didn't tell me that that's a big no no",
            "big mistake so what's your address and where are you located",
            "to legal name your number and the time you call please feel free to and we'll return your call as "
            "soon as possible god bless and have a nice day sorry hello this is the",
            "like so what's your address and where you located",
            "please tell me more",
            "i don't consent to be recorded and you don't tell me that that's a big no-no",
            "please say your name the legal name of the entity responsible for the call and your "
            "contact address and phone number",
            "you better know what that means",
            "that means",
        ],
        "AM": ["whoops"],
        "N-": ["and now", "nah", "now", "now thank you", "know", "known"],
        "N": [
            "ooh",
            "like",
            "mmm",
            "ah",
            "um",
            "blue",
            "it",
            "go",
            "options",
            "out",
            "oh",
            "cheers",
            "i",
            "hell",
            "hall",
            "at all",
            "get out",
            "nelo",
            "hella",
            "self",
            "hella hella",
            "hate",
            "hellu",
            "hella out",
            "devil",
            "a-a",
            "aa",
            "hell out",
            "ah",
            "communications hello",
            "mom",
            "Cat",
            "b of medicare",
            "part b of medicare",
        ],
        "P": [
            "guess",
            "is",
            "the hell",
            "store",
            "list",
            "if",
            "hearing",
            "b-s",
            "d-s",
            "c-s",
            "rks",
            "dick",
            "beer",
            "ccs",
            "tricare",
            "jerk",
            "it yet",
            "part a",
            "killer",
            "v-a",
            "va",
            "v-a-a",
        ],
        "silent": [
            "A",
            "B",
            "C",
            "us your options",
            "discuss your options",
            "your options",
            "muffled speaking",
            "trrrr",
            "how old you are",
            "old you are",
            "kissing",
            "piano music",
        ],
        "APM": [
            "sixty-five",
            "sixty-seven",
            "sixty-six",
            "sixty-eight",
            "sixty-nine",
            "nanny",
        ],
    }

    SUBSTRING_SEARCH_DICT = {
        "HP": [
            "i didn't hear it ring",
            "first time I called, I didn't hear it ringing",
            "first time I called, I didn't hear it ring",
            "time I called I didn't hear it ringing",
            "time I called, I didn't hear it ring",
            "The first time I called I didn't",
            "The first time I called I didn't hear it",
            "The first time I called I didn't hear",
            "The first time I called",
            "The first time I called I didn't hear it ringing",
            "The first time I called I didn't hear it ring",
            "i didn't hear it ringing",
            "okay oh",
            "laughing okay",
            "uh okay uh",
            "it okay alright",
            "beep",
            "well how are you i'm doing very well",
            "yes back if i'm gonna perform that",
            "alright okay so alright",
            "all right okay so all right",
            "all right okay so alright",
            "i like this veryoh guys come on  String",
            "i like this very oh guys come on string",
            "sure thing i'll be here if you change your mind",
            "happy birthday all the best",
            "sure thing i'll be here if you change your mind cold sweat smile",
            "i'm old enough that i don't need to answer the question smirk",
            "well it's funny that you should call because my third eldest larissa she was talking about "
            "this just last week and you know she's she's",
            "we're all quite proud of her yes yes so yeah she was saying that i should look you know "
            "get into the look into this sort of thing so what more can you tell me about it",
            "oh yes yes someone did say last week that someone did call last week about the same thing "
            "was that you",
            "well it's funny that you should call because my third eldest larissa she was talking about "
            "this just last week and you know she's she's very smart",
            "out of her yes yes so yes she was saying that i should look you know get into the look "
            "into this sort of thing so what more can you tell me about it",
            "i prefer not to answer with a number i know i'm young cool smiling face with hearts",
            "sure thing i'll be here if you change your mind cold sweat smile",
            "and down the music there i love show tunes what's your favorite music",
            "what's your favorite music",
            "assuming everything 'cause we did try this a couple of weeks ago",
            "alright and I'm assuming everything 'cause we did try this a couple of weeks ago",
            "can you just scream karate chop on top of your lungs right now it's just really something important",
            "karate chop on top of your lungs right now",
            "top of your lungs right now it's just really something",
            "you just scream karate chop on top of your",
            "and hear it ringed",
            "hear it ringed",
            "sure thing i'll be here if you change your mind",
            "happy birthday and i really mean it all the best",
            "good morning good morning",
            "you know it keeps going on",
            "I didn't consent to this call",
            "please say your name the legal name of the entity responsible for the call and your contact "
            "address and phone number",
            "okay everything is okay there's a couple of things",
            "i didn't consent",
            "i didn't consent",
            "legal name",
            "this is an unwanted call",
            "consent",
        ],
        "LB": [
            "speaking in foreign language",
            "speaks in foreign language",
            "speaks foreign language",
            "foreign language",
            "speaking foreign language",
            "speaking spanish",
            "bueno",
        ],
        "APM": [
            "ab1",
            "ab2",
            "ab3",
            "ab4",
            "ab5",
            "ab6",
            "ab7",
            "ab8",
            "ab9",
            "sixty-seven",
            "sixty-six",
            "sixty-eight",
            "sixty-nine",
        ],
        "APA": ["i'm under the age of sixty-five", "i'm under age of sixty-five"],
        "silent": [
            "unintelligible",
            "mumbles",
            "electronic music",
            "audio cuts out",
            "swish",
            "swoosh",
            "BLANK AUDIO",
            "inaudible",
            "BLANK_AUDIO",
            "grunting",
            "mumbling",
            "blankaudio",
            "blank audio",
            "i'll see you in the next video",
            "thank you for watching",
            "i'll see you next time",
        ],
        "AM": ["phone beeping", "phone beeps", "beep", "beeping", "beeps"],
    }

    CONTRACTIONS = {
        "cannot": "can't",
        "will not": "won't",
        "do not": "don't",
        "i am": "I'm",
        "he is": "he's",
        "he has": "he's",
        "she is": "she's",
        "she has": "she's",
        "it is": "it's",
        "it has": "it's",
        "that is": "that's",
        "there is": "there's",
        "there has": "there's",
        "who is": "who's",
        "who has": "who's",
        "what is": "what's",
        "what has": "what's",
        "where is": "where's",
        "where has": "where's",
        "how is": "how's",
        "how has": "how's",
        "let us": "let's",
        "i have": "I've",
        "you have": "you've",
        "we have": "we've",
        "they have": "they've",
        "i will": "I'll",
        "i shall": "I'll",
        "you will": "you'll",
        "he will": "he'll",
        "she will": "she'll",
        "it will": "it'll",
        "we will": "we'll",
        "they will": "they'll",
        "is not": "isn't",
        "are not": "aren't",
        "was not": "wasn't",
        "were not": "weren't",
        "have not": "haven't",
        "has not": "hasn't",
        "had not": "hadn't",
        "would not": "wouldn't",
        "does not": "doesn't",
        "did not": "didn't",
        "could not": "couldn't",
        "should not": "shouldn't",
        "might not": "mightn't",
        "must not": "mustn't",
        "'em": "them",
        "quick calling": "quit calling",
        "nanny": "ninety",
    }


def get_settings() -> Settings:
    return Settings()


settings = get_settings()
